export const PLANS = [
  {
    id: 'basico',
    name: 'Básico',
    monthlyPrice: 349,
    annualPrice: 3490,
    annualSaving: 698,
    includedBranches: 1,
    extraBranchPrice: 149,
    badge: null,
    hardware: null,
    features: [
      'POS & Ventas',
      'Inventario',
      'Crédito y Cobranza',
      'Finanzas y Reportes',
      'Gestión de Usuarios (5 roles)',
      'Multi-empresa',
      'Soporte técnico',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    monthlyPrice: 699,
    annualPrice: 6990,
    annualSaving: 1398,
    includedBranches: 3,
    extraBranchPrice: 129,
    badge: 'Más popular',
    hardware: null,
    features: [
      'Todo lo del plan Básico',
      'Reportes avanzados',
      'Análisis de tendencias',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    monthlyPrice: 999,
    annualPrice: 9990,
    annualSaving: 1998,
    includedBranches: 5,
    extraBranchPrice: 99,
    badge: 'Completo',
    hardware: null,
    features: [
      'Todo lo del plan Premium',
      'Hasta 5 sucursales',
      'Precio preferencial por sucursal extra: +$99/mes',
    ],
  },
  {
    id: 'all-inclusive',
    name: 'All-Inclusive',
    monthlyPrice: 1299,
    annualPrice: 12990,
    annualSaving: 2598,
    includedBranches: 5,
    extraBranchPrice: 99,
    badge: 'Todo incluido',
    renewalNote: 'Al finalizar el año, puedes renovar tu equipo o continuar con el plan Enterprise a $999/mes.',
    hardware: {
      contado: { initialFee: 0, monthly: 1299 },
      financiado: { initialFee: 0, monthly: 1682, noteAfterMonth12: 1299 },
    },
    features: [
      'Todo lo del plan Enterprise',
      'Hardware completo incluido (PC o laptop, escáner, impresora de ticket, caja de dinero)',
      'Instalación y configuración incluida',
      'Hasta 5 sucursales',
      'Precio preferencial: +$99/mes por sucursal extra',
    ],
  },
  {
    id: 'starter',
    name: 'Starter',
    monthlyPrice: 349,
    annualPrice: 3490,
    annualSaving: 698,
    includedBranches: 1,
    extraBranchPrice: 149,
    badge: null,
    hardware: { description: 'Escáner de código de barras', initialFee: 799 },
    features: [
      'Todo lo del plan Básico',
      'Escáner de código de barras incluido',
      'Instalación incluida',
    ],
  },
  {
    id: 'duo',
    name: 'Dúo',
    monthlyPrice: 349,
    annualPrice: 3490,
    annualSaving: 698,
    includedBranches: 1,
    extraBranchPrice: 149,
    badge: null,
    hardware: { description: 'Escáner de código de barras + impresora', initialFee: 1299 },
    features: [
      'Todo lo del plan Básico',
      'Escáner de código de barras + impresora incluidos',
      'Instalación incluida',
    ],
  },
  {
    id: 'pro-caja',
    name: 'Pro-Caja',
    monthlyPrice: 349,
    annualPrice: 3490,
    annualSaving: 698,
    includedBranches: 1,
    extraBranchPrice: 149,
    badge: null,
    hardware: { description: 'Escáner + impresora + caja de dinero', initialFee: 1999 },
    features: [
      'Todo lo del plan Básico',
      'Escáner + impresora + caja de dinero incluidos',
      'Instalación incluida',
    ],
  },
];

export const TERMS = {
  billingCycle: 'Mensual (misma fecha cada mes)',
  cancellationPolicy:
    'El cliente puede cancelar desde su panel con 30 días de aviso previo. No se realizan reembolsos por períodos ya facturados.',
  refundPolicy:
    'Según política de Openpay y términos de servicio de Ankode. Aplica para cobros duplicados o errores técnicos comprobables.',
  currency: 'Pesos Mexicanos (MXN) con IVA incluido',
  renewalType: 'Automática vía token guardado en Openpay',
  annualNote:
    'Al contratar plan anual pagas 10 mensualidades y recibes 12 meses de servicio (2 meses gratis — ahorro del 16.7%)',
  dataPolicy:
    'Los datos de tarjeta son tokenizados directamente por Openpay. Ankode nunca almacena datos de pago.',
  supportEmail: 'ankodemx@gmail.com',
};
