export const PLANS = [
  {
    id: 'basico',
    name: 'Básico',
    monthlyPrice: 349,
    annualPrice: 3490,
    annualSaving: 698,
    includedBranches: 1,
    extraBranchPrice: 149,
    badge: null,
    features: [
      'POS & Ventas',
      'Inventario',
      'Crédito y Cobranza',
      'Finanzas y Reportes',
      'Gestión de Usuarios (5 roles)',
      'Multi-empresa',
      'Soporte técnico',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    monthlyPrice: 699,
    annualPrice: 6990,
    annualSaving: 1398,
    includedBranches: 3,
    extraBranchPrice: 129,
    badge: 'Más popular',
    features: [
      'POS & Ventas',
      'Inventario',
      'Crédito y Cobranza',
      'Finanzas y Reportes',
      'Gestión de Usuarios (5 roles)',
      'Multi-empresa',
      'Soporte técnico',
      'Reportes avanzados por período',
      'Análisis de tendencias de ventas',
      'Hasta 3 sucursales incluidas',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    monthlyPrice: 999,
    annualPrice: 9990,
    annualSaving: 1998,
    includedBranches: 5,
    extraBranchPrice: 99,
    badge: 'Completo',
    features: [
        'POS & Ventas',
        'Inventario',
        'Crédito y Cobranza',
        'Finanzas y Reportes',
        'Gestión de Usuarios (5 roles)',
        'Multi-empresa',
        'Soporte técnico',
        'Reportes avanzados y análisis de tendencias',
        'Hasta 5 sucursales incluidas',
        'Precio preferencial por sucursal extra: +$99/mes',
    ],
  },
  {
    id: 'all-inclusive',
    name: 'All-Inclusive',
    monthlyPrice: 1299,
    annualPrice: 12990,
    annualSaving: 2598,
    includedBranches: 5,
    extraBranchPrice: 99,
    badge: 'Todo incluido',
    features: [
      'POS & Ventas',
      'Inventario',
      'Crédito y Cobranza',
      'Finanzas y Reportes',
      'Gestión de Usuarios (5 roles)',
      'Multi-empresa',
      'Soporte técnico',
      'Reportes avanzados y análisis de tendencias',
      'Hasta 5 sucursales incluidas',
      'Precio preferencial por sucursal extra: +$99/mes',
    ],
  },
];

export const TERMS = {
  billingCycle: 'Mensual (misma fecha cada mes)',
  cancellationPolicy:
    'El cliente puede cancelar desde su panel con 30 días de aviso previo. No se realizan reembolsos por períodos ya facturados.',
  refundPolicy:
    'Según política de Openpay y términos de servicio de Ankode. Aplica para cobros duplicados o errores técnicos comprobables.',
  currency: 'Pesos Mexicanos (MXN) con IVA incluido',
  renewalType: 'Automática vía token guardado en Openpay',
  annualNote:
    'Al contratar plan anual pagas 10 mensualidades y recibes 12 meses de servicio (2 meses gratis — ahorro del 16.7%)',
  dataPolicy:
    'Los datos de tarjeta son tokenizados directamente por Openpay. Ankode nunca almacena datos de pago.',
  supportEmail: 'ankodemx@gmail.com',
};
